<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>true</ImplicitUsings>
    
    <IncludeBuildOutput>false</IncludeBuildOutput>
	<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	<IsRoslynComponent>true</IsRoslynComponent>
  </PropertyGroup>

  <ItemGroup>
	<None Include="./README.md" Pack="true" PackagePath="" />
	<None Include="../LICENSE" Pack="true" PackagePath="/" />
	<None Include="./icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <!-- The following libraries include the source generator interfaces and types we need -->
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="IsExternalInit">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	<PackageReference Include="Cubusky.BuildingBlocks" />
  </ItemGroup>

  <!-- This ensures the library will be packaged as a source generator when we use `dotnet pack` -->
  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

</Project>
