using Chickensoft.Collections;
using Chickensoft.Sync;
using Cubusky.BuildingBlocks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Cubusky.Stats.Generators;

[Generator]
[SuppressMessage
(
    "MicrosoftCodeAnalysisCorrectness",
    "RS1041:Compiler extensions should be implemented in assemblies targeting netstandard2.0",
    Justification = """
        We want to reference the names of interfaces from Cubusky.BuildingBlocks, which is restricted to netstandard2.1.

        Furthermore, .NET Standard 2.1 can be used under the following conditions:
        1. The generator will work during builds with .NET tooling (e.g. dotnet build or dotnet msbuild), but will not work for builds with .NET Framework tooling (e.g. msbuild)
        2. The generator will not work for IDE scenarios, which includes builds within Visual Studio and all IntelliSense functionality
        """
)]
public sealed class StatGenerator : IIncrementalGenerator
{
    public static class TrackingName
    {
        public const string StatsToGenerate = nameof(StatsToGenerate);
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource($"{StatAttribute.TypeName}.g.cs", $$"""
                // <auto-generated/>
                namespace {{StatAttribute.Namespace}}
                {
                    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                    internal class {{StatAttribute.TypeName}} : global::System.Attribute { }
                }
                """);
        });

        IncrementalValuesProvider<StatToGenerate> statsToGenerate = context.SyntaxProvider.ForAttributeWithMetadataName
        (
            StatAttribute.FullTypeName,
            predicate: static (node, _) => node is ClassDeclarationSyntax
                or RecordDeclarationSyntax { ClassOrStructKeyword.RawKind: not (int)SyntaxKind.StructKeyword },
            transform: static (ctx, _) => new StatToGenerate((ctx.TargetSymbol as INamedTypeSymbol)!)
        )
        .WithTrackingName(TrackingName.StatsToGenerate);

        context.RegisterSourceOutput(statsToGenerate, Execute);
    }

    private static void Execute(SourceProductionContext context, StatToGenerate statToGenerate)
    {
        var operationName = nameof(IOperation<>)[1..];
        var broadcastName = nameof(IBroadcast<>)[1..];

        var operationTypeParameter = 'T' + operationName;
        var broadcastTypeParameter = 'T' + broadcastName;
        var operationParameter = operationName.Uncapitalize();
        var broadcastParameter = broadcastName.Uncapitalize();

        var operationInterface = $"{nameof(IOperation<>)}<{statToGenerate.TypeName}>";
        var performOpType = $"{nameof(PerformOp<>)}<{statToGenerate.TypeName}>";
        var operationCallbackType = $"{nameof(OperationCallback<,>)}<{statToGenerate.TypeName}, {operationTypeParameter}>";
        var performInterface = $"{nameof(IPerform<>)}<{performOpType}>";

        var operatorInterface = $"{nameof(IOperator<>)}<{statToGenerate.TypeName}>";
        var boxlessQueueType = $"{nameof(BoxlessQueue<>)}<{nameof(IOperation<>)}<{statToGenerate.TypeName}>>";

        var broadcasterInterface = $"{nameof(IBroadcaster<>)}<{statToGenerate.TypeName}>";
        var bindingInterface = $"{nameof(IBinding<,>)}<{statToGenerate.TypeName}, Binding>";

        var callbackParameter = nameof(Callback<>).Uncapitalize();
        var conditionParameter = nameof(Condition<>).Uncapitalize();

        // Blackboard.Has/Get are only inherited (and thus only need `new`) once a [Stat] ancestor already
        // declares them; root types are the first to declare them and must not redeclare with `new`.
        var staticNewModifier = statToGenerate.IsDerived ? "new " : "";

        // Root types must implement this partial property themselves (e.g. `=> _subject;`), giving the
        // compiler a real, type-checked contract instead of a string-named member. Derived types simply
        // inherit the (already-implemented) property from their nearest [Stat] ancestor, so nothing
        // needs to be (re)declared here.
        var subjectDeclaration = statToGenerate.IsDerived
            ? null
            : $$"""
                protected partial {{nameof(SyncSubject)}} Subject { get; }
                """;

        // Broadcaster/Binding are always fixed-named and fully generator-owned: derived types chain to
        // their base type's nested type (mirroring the class hierarchy) instead of requiring the same
        // hand-written boilerplate (base type, constructor) at every level.
        var broadcasterDeclaration = statToGenerate.IsDerived
            ? $$"""
                public new partial class Broadcaster : {{statToGenerate.BaseTypeName}}.Broadcaster, {{broadcasterInterface}}
                {
                    internal Broadcaster({{nameof(SyncSubject)}} subject) : base(subject) { }

                    void {{broadcasterInterface}}.{{nameof(IBroadcaster<>.Broadcast)}}<{{broadcastTypeParameter}}>(in {{broadcastTypeParameter}} {{broadcastParameter}})
                    {
                        Subject.{{nameof(SyncSubject.Broadcast)}}({{broadcastParameter}});
                    }
                }
                """
            : $$"""
                public partial class Broadcaster : {{broadcasterInterface}}
                {
                    protected {{nameof(SyncSubject)}} Subject { get; }

                    internal Broadcaster({{nameof(SyncSubject)}} subject) => Subject = subject;

                    void {{broadcasterInterface}}.{{nameof(IBroadcaster<>.Broadcast)}}<{{broadcastTypeParameter}}>(in {{broadcastTypeParameter}} {{broadcastParameter}})
                    {
                        Subject.{{nameof(SyncSubject.Broadcast)}}({{broadcastParameter}});
                    }
                }
                """;

        var bindingDeclaration = statToGenerate.IsDerived
            ? $$"""
                public new partial class Binding : {{statToGenerate.BaseTypeName}}.Binding, {{bindingInterface}}
                {
                    internal Binding({{nameof(ISyncSubject)}} subject) : base(subject) { }

                    Binding {{bindingInterface}}.{{nameof(IBinding<,>.On)}}<{{broadcastTypeParameter}}>({{nameof(Callback<>)}}<{{broadcastTypeParameter}}> {{callbackParameter}}, {{nameof(Condition<>)}}<{{broadcastTypeParameter}}>? {{conditionParameter}})
                    {
                        AddCallback({{callbackParameter}}, {{conditionParameter}});
                        return this;
                    }
                }
                """
            : $$"""
                public partial class Binding : {{nameof(SyncBinding)}}, {{bindingInterface}}
                {
                    internal Binding(ISyncSubject subject) : base(subject) { }

                    Binding {{bindingInterface}}.{{nameof(IBinding<,>.On)}}<{{broadcastTypeParameter}}>({{nameof(Callback<>)}}<{{broadcastTypeParameter}}> {{callbackParameter}}, {{nameof(Condition<>)}}<{{broadcastTypeParameter}}>? {{conditionParameter}})
                    {
                        AddCallback({{callbackParameter}}, {{conditionParameter}});
                        return this;
                    }
                }
                """;

        // Every block below is self-contained and flush-left (column 0), with only its own *relative*
        // nesting (e.g. method bodies) indented. This lets us correctly re-indent the whole class body as
        // a unit once, rather than trying to hand-align dozens of interpolated members at their eventual
        // (and variable, depending on namespace/containing-type nesting) depth.
        var classMembers = string.Join("\n\n", new[]
        {
            $$"""
            private static readonly {{nameof(Blackboard)}} __defaultOperationCallbacks = new {{nameof(Blackboard)}}();
            """,
            $$"""
            public static void {{nameof(Blackboard.Set)}}<{{operationTypeParameter}}>({{operationCallbackType}} {{operationParameter}})
                where {{operationTypeParameter}} : struct, {{operationInterface}}
            {
                __defaultOperationCallbacks.{{nameof(Blackboard.Set)}}({{operationParameter}});
            }
            """,
            $$"""
            public static void {{nameof(Blackboard.Overwrite)}}<{{operationTypeParameter}}>({{operationCallbackType}} {{operationParameter}})
                where {{operationTypeParameter}} : struct, {{operationInterface}}
            {
                __defaultOperationCallbacks.{{nameof(Blackboard.Overwrite)}}({{operationParameter}});
            }
            """,
            $$"""
            public static {{staticNewModifier}}bool {{nameof(Blackboard.Has)}}<{{operationTypeParameter}}>()
                where {{operationTypeParameter}} : struct, {{operationInterface}}
            {
                return __defaultOperationCallbacks.{{nameof(Blackboard.Has)}}<{{operationCallbackType}}>();
            }
            """,
            $$"""
            public static {{staticNewModifier}}{{operationCallbackType}} {{nameof(Blackboard.Get)}}<{{operationTypeParameter}}>()
                where {{operationTypeParameter}} : struct, {{operationInterface}}
            {
                return __defaultOperationCallbacks.{{nameof(Blackboard.Get)}}<{{operationCallbackType}}>();
            }
            """,
            subjectDeclaration,
            $$"""
            private readonly {{boxlessQueueType}} __operationQueue = new {{boxlessQueueType}}();
            private Broadcaster? __operationBroadcaster;
            private Broadcaster __OperationBroadcaster => __operationBroadcaster ??= new Broadcaster(Subject);
            """,
            $$"""
            void {{operatorInterface}}.{{nameof(IOperator<>.Perform)}}<{{operationTypeParameter}}>(in {{operationTypeParameter}} {{operationParameter}})
            {
                __operationQueue.Enqueue({{operationParameter}});
                Subject.{{nameof(ISyncSubject.Perform)}}(new {{performOpType}}(this, __defaultOperationCallbacks, __OperationBroadcaster));
            }
            """,
            $$"""
            void {{performInterface}}.{{nameof(IPerform<>.Perform)}}(in {{performOpType}} op)
            {
                __operationQueue.Dequeue(op);
            }
            """,
            broadcasterDeclaration,
            bindingDeclaration,
        }.OfType<string>());

        string classDeclaration = $$"""
            public partial class {{statToGenerate.TypeName}} : {{performInterface}}, {{operatorInterface}}
            {
            {{Indent(classMembers, 1)}}
            }
            """;

        // Re-declare each containing type (and, below, the namespace) as a matching partial wrapper so the
        // generated members land on the actual nested type instead of an unrelated top-level type of the
        // same name. Containing types are ordered outermost-first, i.e. in the exact order they need to be
        // opened here.
        //
        // The class declaration is indented exactly once for the total wrapper depth (instead of once per
        // wrapper, which would re-scan/rebuild the whole - and ever-growing - body at every level), while the
        // (single-line) opening/closing braces are indented directly at their own, already-known level.
        var openings = new StringBuilder();
        var level = 0;

        if (statToGenerate.Namespace is string @namespace)
        {
            openings.Append(Indent($"namespace {@namespace}\n{{", level++)).Append('\n');
        }

        foreach (var containingType in statToGenerate.ContainingTypes)
        {
            openings.Append(Indent($"partial {containingType.Keyword} {containingType.Declaration}\n{{", level++)).Append('\n');
        }

        // `level` now equals the total wrapper depth, so it doubles as the class declaration's indent.
        var indentedClassDeclaration = Indent(classDeclaration, level);

        var closings = new StringBuilder();
        while (level > 0)
        {
            closings.Append(Indent("}", --level)).Append('\n');
        }

        var body = $"{openings}{indentedClassDeclaration}\n{closings}";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using {{nameof(Chickensoft)}}.{{nameof(Chickensoft.Collections)}};
            using {{nameof(Chickensoft)}}.{{nameof(Chickensoft.Sync)}};
            using {{nameof(Cubusky)}}.{{nameof(BuildingBlocks)}};

            {{body}}
            """;

        context.AddSource($"{statToGenerate.ClassName}.g.cs", source);
    }

    /// <summary>Indents every non-empty line of <paramref name="text"/> by <paramref name="levels"/> * 4 spaces.</summary>
    private static string Indent(string text, int levels)
    {
        if (levels <= 0 || text.Length == 0)
        {
            return text;
        }

        var prefix = new string(' ', levels * 4);
        var lines = text.Replace("\r\n", "\n").Split('\n');

        var builder = new StringBuilder(text.Length + prefix.Length * lines.Length);
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i];

            // Don't add trailing whitespace to otherwise-empty lines.
            if (line.Length > 0)
            {
                builder.Append(prefix);
            }

            builder.Append(line);

            // Every line except the last one was originally followed by a newline; put it back.
            var isLastLine = i == lines.Length - 1;
            if (!isLastLine)
            {
                builder.Append('\n');
            }
        }

        return builder.ToString();
    }
}

internal static class StringExtensions
{
    public static string Uncapitalize(this string str) =>
        !string.IsNullOrEmpty(str) && char.IsUpper(str[0])
        ? char.ToLowerInvariant(str[0]) + str[1..]
        : str;
}
