name: "📦 BuildingBlocks Release"
on:
  # Make a release whenever the developer wants.
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "The version in the format X.Y.Z to release"
        required: true
  # Make a release whenever we're told to by another workflow.
  workflow_call:
    secrets:
      NUGET_API_KEY_BUILDINGBLOCKS:
        description: "BuildingBlocks API key for Nuget"
        required: true
    # Input unifies with the workflow dispatch since it's identical.
    inputs:
      version:
        type: string
        description: "The version in the format X.Y.Z to release"
        required: true
jobs:
  release:
    name: "📦 BuildingBlocks Release"
    runs-on: ubuntu-latest
    if: github.repository == 'Cubusky/Stats'
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    permissions:
      id-token: write
    steps:
      - name: Validate version input
        id: validate-version
        uses: robandpdx/check-value-regex@v1.0.2
        with:
          input: ${{ inputs.version }}
          regex: '^\d+\.\d+\.\d+$'

      - name: Fail if version input is invalid
        if: steps.validate-version.outputs.matches == 'false'
        run: |
          echo "Invalid version input: ${{ inputs.version }}. Must be in the format 'X.Y.Z'."
          exit 1

      - name: 🧾 Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          submodules: "recursive"
          fetch-depth: 0 # So we can get all tags.

      - uses: actions/setup-dotnet@v5
        name: 💽 Setup .NET SDK
        with:
          # Use the .NET SDK from global.json in the root of the repository.
          global-json-file: global.json

      # Write version to file so .NET will build correct version.
      - name: 📝 Write Version to File
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "0.0.0-devbuild"
          replace: ${{ inputs.version }}
          regex: false
          include: Cubusky.BuildingBlocks/Cubusky.BuildingBlocks.csproj

      - name: 📦 Build
        working-directory: Cubusky.BuildingBlocks
        run: dotnet build -c Release

      - name: 🔎 Get Package Path
        id: package-path
        run: |
          package=$(find ./Cubusky.BuildingBlocks/nupkg -name "*.nupkg")
          echo "package=$package" >> "$GITHUB_OUTPUT"
          echo "📦 Found package: $package"

      - name: 🔑 Get NuGet Key
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: 🛜 Publish to NuGet
        run: |
          dotnet nuget push "${{ steps.package-path.outputs.package }}" \
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
            --source "https://api.nuget.org/v3/index.json" --skip-duplicate
